from typing import Final, Protocol
from uuid import UUID

__version__: Final[str]

class HasBytes(Protocol):
    bytes: bytes

def randomize() -> UUID: ...
def get_machine() -> UUID: ...
def get_machine_app_specific(uuid: UUID | HasBytes) -> UUID: ...
def get_boot() -> UUID: ...
